In [2]:
import pandas as pd 
import os

In [3]:
os.getcwd()
parent_path=os.path.abspath(os.path.join(os.getcwd(),".."))
file_name = "orders_10m.csv"
base_path=os.path.join(parent_path , "otherfile")
file_path= os.path.join(base_path, file_name)
print(file_path)

df  =pd.read_csv(file_path)
df.head()

d:\Project\KrishnaRAGUdemy\otherfile\orders_10m.csv

,order_id,customer_id,product_id,price,order_date,order_status,state,quantity
0,1,124550,38,134.37,2020-03-23,PLACED,Haryana,2
1,2,32801,40,106.00,2009-04-20,RETURNED,Tamil Nadu,1
2,3,467993,48,102.51,2003-02-06,PLACED,Chhattisgarh,3
3,4,620337,40,106.50,2019-05-07,PLACED,Punjab,1
4,5,653851,36,105.54,2002-09-15,PLACED,Rajasthan,3

In [4]:
data = {
    "name" : ["A","b","C","D"] , 
    "roll_no" : [1,2,3,4] , 
    "category" : ["products","seminar", "cartoon","films"]
    
}

df = pd.DataFrame(data)
df.head()

  name  roll_no  category
0    A        1  products
1    b        2   seminar
2    C        3   cartoon
3    D        4     films

In [8]:
with pd.ExcelWriter(f'{base_path}/newfile.xlsx',engine='xlsxwriter') as writer:
    df.to_excel(writer,sheet_name="orders",index=False)

    workbook = writer.book
    workbook.set_properties( { "Title": "orders", 
                              "Subject": "vineet orders data", 
                              "Owner": "vineet", 
                              "Description": "this is orders data" ,
                              "last_modified_by": "vineet"})

### Baad mei kabhi kaam ayega how to read metadata forthe file

In [10]:
from openpyxl import load_workbook
wb = load_workbook(f'{base_path}/newfile.xlsx')
props = wb.properties

print("Title:", props.title)
print("Subject:", props.subject)
print("Description:", props.description)
print("Owner:", props.creator)
print("Last Modified By:", props.lastModifiedBy)

Title: None
Subject: None
Description: None
Owner: None
Last Modified By: None