In [ ]:
import pandas as pd 
import os

In [2]:
os.getcwd()
parent_path=os.path.abspath(os.path.join(os.getcwd(),".."))
file_name = "orders_10m.csv"
base_path=os.path.join(parent_path , "otherfile")
file_path= os.path.join(base_path, file_name)
print(file_path)

orders_df  =pd.read_csv(file_path)
orders_df.head()

d:\Project\KrishnaRAGUdemy\otherfile\orders_10m.csv

,order_id,customer_id,product_id,price,order_date,order_status,state,quantity
0,1,124550,38,134.37,2020-03-23,PLACED,Haryana,2
1,2,32801,40,106.00,2009-04-20,RETURNED,Tamil Nadu,1
2,3,467993,48,102.51,2003-02-06,PLACED,Chhattisgarh,3
3,4,620337,40,106.50,2019-05-07,PLACED,Punjab,1
4,5,653851,36,105.54,2002-09-15,PLACED,Rajasthan,3

In [3]:
data = {
    "name" : ["A","b","C","D"] , 
    "roll_no" : [1,2,3,4] , 
    "category" : ["products","seminar", "cartoon","films"]
    
}

df = pd.DataFrame(data)
df.head()

  name  roll_no  category
0    A        1  products
1    b        2   seminar
2    C        3   cartoon
3    D        4     films

In [4]:
with pd.ExcelWriter(f'{base_path}/newfile.xlsx',engine='xlsxwriter') as writer:
    df.to_excel(writer,sheet_name="orders",index=False)

    workbook = writer.book
    workbook.set_properties( { "Title": "orders", 
                              "Subject": "vineet orders data", 
                              "Owner": "vineet", 
                              "Description": "this is orders data" ,
                              "last_modified_by": "vineet"})

In [5]:
with pd.ExcelWriter(f'{base_path}/orders.xlsx',engine='xlsxwriter') as writer:
    orders_df.iloc[0:100_00,:].to_excel(writer,sheet_name="orders",index=False)

### Baad mei kabhi kaam ayega how to read metadata forthe file

In [6]:
from openpyxl import load_workbook
wb = load_workbook(f'{base_path}/newfile.xlsx')
props = wb.properties

print("Title:", props.title)
print("Subject:", props.subject)
print("Description:", props.description)
print("Owner:", props.creator)
print("Last Modified By:", props.lastModifiedBy)

Title: None
Subject: None
Description: None
Owner: None
Last Modified By: None

### Excel and CSV Parsing Techinques

In [7]:
from langchain_community.document_loaders import CSVLoader, UnstructuredCSVLoader

C:\Users\vinee\AppData\Local\Temp\ipykernel_1360\444435838.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import CSVLoader, UnstructuredCSVLoader
d:\Project\KrishnaRAGUdemy\rag\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
unstructuredcsv = UnstructuredCSVLoader(file_path=file_path,mode="elements")
documents =unstructuredcsv.load()
print(f'Metadata infromation >>>>>')


for i , doc in enumerate(documents):
    print(f"\n Element {i+1}")
    print(f'Content :  {doc.page_content[:20]}')
    print(f'Metadata : doc.metadata')

d:\Project\KrishnaRAGUdemy\rag\Lib\site-packages\unstructured\partition\csv.py:65: DtypeWarning: Columns (0: 0, 1: 1, 2: 2, 3: 3, 4: 7) have mixed types. Specify dtype option on import or set low_memory=False.
  dataframe = pd.read_csv(file, **read_kw)

XMLSyntaxError: switching encoding: encoder error, line 1, column 1 (<string>, line 1)

In [ ]:
csvobject  = CSVLoader(file_path)
documents =csvobject.load()
print(f'No of documents loaded {len(documents)}')
print(f'Content {documents[0].page_content[:40]}')

### UserDefined advanced CSV or Excel Parsing

In [15]:
from typing import List
from langchain_core.documents  import Document
def process_excel_advance_way(file_path:str)->List[Document] :
    documents=[]
    # Read all the sheets
    excel_file=pd.ExcelFile(file_path,engine="openpyxl")
    print(excel_file.sheet_names)

    for sheet  in excel_file.sheet_names:
        df = pd.read_excel(file_path,sheet_name=sheet )
        df.head()
        content = f'Rows : {len(df)}'
        content +=f'Columns : {df.columns}'
        content += df.to_string()
        content +=' Other infromation  {df.info()}'

        metadata = { "source" : f"{file_path}" , 
                    "sheet_name" :f'{sheet}' , 
                    "no of rows" : f"{len(df)}", 
                    "num_columns" : f"{len(df.columns)}"                    
                    }
        doc = Document(metadata=metadata, page_content =content)
        documents.append(doc)

    return documents

In [21]:
base_path= os.path.abspath( os.path.join(os.getcwd() , ".."))
folder_name = "otherfile"
file_name="orders.xlsx"
file_path = os.path.join(base_path , folder_name , file_name)
print(file_path)

d:\Project\KrishnaRAGUdemy\otherfile\orders.xlsx

In [ ]:
try:
    file_name = "orders.xlsx"
    
    documents = process_excel_advance_way(file_path)
    print(len(documents))
    for k , v in documents[0].metadata.items():
        print(f' Key : {k} , Value: {v}')

    print(f'Content: {documents[0].page_content}[:100]')
except Exception as e:
    print(f'Error {e}')

['orders']
1
 Key : source , Value: d:\Project\KrishnaRAGUdemy\otherfile\orders.xlsx
 Key : sheet_name , Value: orders
 Key : no of rows , Value: 10000
 Key : num_columns , Value: 8
Content: Rows : 10000Columns : Index(['order_id', 'customer_id', 'product_id', 'price', 'order_date',
       'order_status', 'state', 'quantity'],
      dtype='str')      order_id  customer_id  product_id   price  order_date order_status             state  quantity
0            1       124550          38  134.37  2020-03-23       PLACED           Haryana         2
1            2        32801          40  106.00  2009-04-20     RETURNED        Tamil Nadu         1
2            3       467993          48  102.51  2003-02-06       PLACED      Chhattisgarh         3
3            4       620337          40  106.50  2019-05-07       PLACED            Punjab         1
4            5       653851          36  105.54  2002-09-15       PLACED         Rajasthan         3
5            6       473391          30  154.42  2013-10-29       PLACED             Delhi         2
6            7       244490          11  156.35  2001-01-31       PLACED            Odisha         2
7            8       937384          20  199.87  2011-10-26       PLACED             Delhi         2
8            9       927946          13  188.11  2018-03-17      SHIPPED       Maharashtra         2
9           10       865272          91  178.54  2012-03-29    DELIVERED             Assam         3
10          11       696365          28  160.06  2009-02-01      SHIPPED         Karnataka         3
11          12       435772          74  163.62  2021-06-14       PLACED             Assam         2
12          13       778894          26  162.94  2020-05-14      SHIPPED            Odisha         1
13          14        70715          31  136.89  2021-06-06       PLACED        Tamil Nadu         3
14          15       211552          83  101.41  2002-09-29      SHIPPED       West Bengal         3
15          16       132322          53  109.34  2024-05-16       PLACED         Telangana         1
16          17       625249          39  162.35  2007-05-12       PLACED           Gujarat         1
17          18       869101          20  131.38  2020-10-12      SHIPPED         Telangana         1
18          19       723527          79  176.97  2002-09-21    DELIVERED         Telangana         2
19          20       752102          39  168.82  2015-09-02      SHIPPED            Kerala         3
20          21        32953          68  129.41  2002-05-20     RETURNED       West Bengal         3
21          22       436799          15  107.74  2023-11-23    CANCELLED            Punjab         3
22          23       974519          50  104.96  2009-06-02    DELIVERED            Punjab         2
23          24       450222          78  164.32  2019-01-24       PLACED               Goa         1
24          25       739145          93  120.10  2009-01-31       PLACED  Himachal Pradesh         3
25          26       850578          82  175.39  2023-06-10      SHIPPED            Punjab         3
26          27       782913          98  171.41  2013-12-22       PLACED      Chhattisgarh         3
27          28       705709          76  162.28  2022-09-24    DELIVERED         Jharkhand         1
28          29       268786          67  170.12  2001-09-30      SHIPPED           Gujarat         1
29          30       732757          75  110.00  2020-03-23    DELIVERED           Haryana         3
30          31       542288          82  136.87  2019-11-22      SHIPPED       West Bengal         2
31          32       238254          79  121.27  2016-10-12    DELIVERED            Kerala         1
32          33        80199          15  123.40  2009-05-19      SHIPPED    Madhya Pradesh         1
33          34       527235          38  140.37  2016-06-21       PLACED            Kerala         2
34          35       744519          72  124.43  2015-09-10      SHIPPED         Karnataka         2
35          36       662801          32  159.74  2024-07-14    DELIVERED            Punjab         3
36          37         6604          69  152.43  2014-11-18      SHIPPED        Tamil Nadu         3
37          38       255564          92  153.75  2007-04-28       PLACED               Goa         3
38          39       364643          15  120.97  2009-01-09       PLACED             Bihar         1
39          40       316263          37  131.12  2002-07-01       PLACED         Rajasthan         1
40          41        29484          61  188.91  2005-10-23    CANCELLED           Haryana         3
41          42       867104          83  198.68  2024-07-21    DELIVERED    Andhra Pradesh         1
42          43       696274          34  114.18  2007-03-13      SHIPPED       Uttarakhand         1
43          44       497148          26  105.60  2007-06-05       PLACED               Goa         3
44          45       908106          80  111.08  2005-02-28      SHIPPED     Uttar Pradesh         1
45          46       875812          44  157.81  2007-09-08      SHIPPED    Madhya Pradesh         1
46          47       245881          73  120.28  2020-08-24     RETURNED       West Bengal         2
47          48        84662          13  113.79  2002-12-31      SHIPPED       Uttarakhand         3
48          49       803663          35  186.79  2020-11-13      SHIPPED           Haryana         3
49          50       124263          43  102.82  2021-08-06    DELIVERED       West Bengal         1
50          51       464794          63  143.47  2022-07-08      SHIPPED       West Bengal         3
51          52       853533          60  118.89  2015-09-22      SHIPPED            Odisha         1
52          53       621933          52  152.62  2020-01-19       PLACED    Madhya Pradesh         3
53          54       960670          22  139.01  2008-12-05      SHIPPED         Jharkhand         1
54          55       691529          87  197.60  2005-10-01      SHIPPED         Jharkhand         3
55          56       477527          76  117.09  2007-06-13      SHIPPED  Himachal Pradesh         2
56          57       465127          24  151.37  2005-06-05       PLACED           Gujarat         3
57          58       156945          41  171.27  2012-01-25    DELIVERED           Haryana         2
58          59       232866          43  188.56  2023-07-12    DELIVERED             Assam         2
59          60        16700          31  151.96  2011-03-30       PLACED        Tamil Nadu         3
60          61       555669          88  115.98  2009-08-24       PLACED         Jharkhand         3
61          62       360184          91  112.11  2004-07-01    DELIVERED  Himachal Pradesh         1
62          63       566303          25  134.57  2012-12-13       PLACED            Odisha         3
63          64       551045          16  148.15  2001-07-19       PLACED            Odisha         1
64          65       754576          65  128.69  2014-02-04       PLACED           Gujarat         2
65          66       774940          40  113.69  2020-05-14    DELIVERED         Jharkhand         1
66          67       656114          98  133.61  2019-02-04      SHIPPED             Assam         1
67          68       886822          97  105.14  2000-01-30       PLACED         Rajasthan         1
68          69       538128          22  177.83  2003-03-20       PLACED    Madhya Pradesh         1
69          70       549145          60  128.21  2011-05-09    DELIVERED            Punjab         1
70          71       855924          97  144.69  2017-02-24      SHIPPED         Karnataka         3
71          72       472138          65  185.41  2012-07-23     RETURNED  Himachal Pradesh         3
72          73       630306          67  131.74  2014-03-07       PLACED  Himachal Pradesh         2
73          74       358009          27  122.53  2020-11-27       PLACED            Kerala         1
74          75       110921          82  105.84  2014-09-19      SHIPPED             Bihar         2
75          76       568407          75  181.59  2006-11-30    DELIVERED       Maharashtra         2
76          77        74926          86  162.73  2019-03-10    DELIVERED         Jharkhand         1
77          78       110743          94  133.28  2023-09-15      SHIPPED    Madhya Pradesh         2
78          79       541298          14  186.42  2023-11-25       PLACED       Uttarakhand         3
79          80       812607          18  166.76  2005-07-15       PLACED       Uttarakhand         3
80          81       681389          46  117.75  2002-05-02       PLACED           Gujarat         1
81          82       594650          53  122.76  2004-05-06       PLACED         Telangana         3
82          83       391868          70  169.64  2010-08-13    DELIVERED           Gujarat         3
83          84        60276          23  114.12  2016-04-06      SHIPPED         Rajasthan         3
84          85       608977          92  171.42  2012-07-06      SHIPPED    Andhra Pradesh         2
85          86       969833           7  157.31  2018-06-12      SHIPPED            Kerala         2
86          87       882079          98  158.01  2000-09-28    DELIVERED     Uttar Pradesh         1
87          88       349301          49  185.18  2000-04-22      SHIPPED         Rajasthan         3
88          89       786598          12  128.33  2011-02-12    DELIVERED       Maharashtra         2
89          90       658759          37  105.25  2001-08-28      SHIPPED             Bihar         3
90          91       155108          13  154.21  2000-07-06    CANCELLED               Goa         1
91          92       825655           2  126.24  2018-01-07     RETURNED               Goa         1
92          93       975377          98  104.56  2009-09-24       PLACED               Goa         2
93          94       391366          84  123.52  2017-08-04       PLACED               Goa         2
94          95       165318           3  140.85  2014-04-24       PLACED            Odisha         2
95          96       937935          32  154.21  2020-01-06    DELIVERED    Madhya Pradesh         2
96          97       232483          77  169.74  2013-10-05      SHIPPED               Goa         1
97          98       642515          86  118.42  2003-05-15       PLACED       Maharashtra         1
98          99       702671          88  102.12  2015-03-29    CANCELLED               Goa         1
99         100       518270          19  195.78  2013-09-26      SHIPPED            Kerala         2
100        101       703421          92  144.00  2003-07-01    DELIVERED         Telangana         3
101        102       829628          58  193.47  2015-04-20       PLACED             Assam         1
102        103       937758          58  105.17  2012-05-27    DELIVERED         Karnataka         1
103        104       925706          97  189.02  2011-07-28      SHIPPED               Goa         3
104        105       345146           5  185.55  2012-08-28       PLACED            Odisha         2
105        106       481263          74  198.16  2023-08-10       PLACED        Tamil Nadu         2
106        107       565651          19  146.59  2004-08-03      SHIPPED         Rajasthan         2
107        108       914818          62  113.91  2014-01-28       PLACED    Madhya Pradesh         2
108        109       621549          26  171.03  2023-09-13       PLACED             Bihar         3
109        110       366836          20  127.27  2020-01-19    DELIVERED         Jharkhand         2
110        111       108257          52  198.72  2007-04-15      SHIPPED         Karnataka         3
111        112       270198           9  146.11  2007-03-15       PLACED             Assam         3
112        113       172626          79  120.66  2013-09-07       PLACED             Bihar         1
113        114       461405          64  141.59  2000-11-02      SHIPPED         Telangana         1
114        115        48873          39  186.25  2017-12-29      SHIPPED           Gujarat         1
115        116       877176          96  157.26  2005-01-01      SHIPPED            Kerala         1
116        117       869701          19  101.42  2010-07-09      SHIPPED            Kerala         2
117        118       660614          76  183.25  2013-11-03    DELIVERED       Maharashtra         3
118        119        50403          51  100.49  2007-11-17    DELIVERED         Karnataka         1
119        120       397543          37  198.55  2015-03-27    DELIVERED            Kerala         3
120        121       124045          13  164.49  2011-07-27      SHIPPED            Odisha         1
121        122       683417          97  158.21  2014-03-24       PLACED    Madhya Pradesh         1
122        123       311190          28  192.71  2021-02-12       PLACED  Himachal Pradesh         3
123        124       819482          81  120.80  2005-08-18       PLACED         Telangana         1
124        125       129546          27  153.58  2017-01-05    CANCELLED               Goa         3
125        126       929435          56  149.39  2000-08-12    DELIVERED         Telangana         1
126        127        95028          61  172.97  2017-11-20       PLACED           Haryana         1
127        128       900457          97  112.87  2013-03-01    DELIVERED             Assam         3
128        129       534577          34  116.92  2006-01-14       PLACED            Odisha         3
129        130        73136          25  170.54  2001-07-25    DELIVERED       Maharashtra         3
130        131       723152          34  153.35  2000-02-18       PLACED    Madhya Pradesh         2
131        132       692044          23  199.74  2018-03-14     RETURNED      Chhattisgarh         1
132        133       743135          37  147.68  2009-10-14      SHIPPED       Maharashtra         3
133        134       457590          40  105.26  2018-02-19      SHIPPED     Uttar Pradesh         1
134        135       983480           6  129.77  2012-10-05    DELIVERED       West Bengal         1
135        136       431353          50  176.40  2014-06-03    CANCELLED           Haryana         1
136        137       205263          58  103.53  2001-05-06    DELIVERED             Bihar         3
137        138       240991          20  124.49  2020-05-02      SHIPPED               Goa         3
138        139       706825          28  124.90  2011-01-28       PLACED         Karnataka         2
139        140       937028          41  122.11  2008-09-18    DELIVERED    Andhra Pradesh         3
140        141       600966           4  100.97  2018-02-06    DELIVERED         Karnataka         2
141        142       488932          55  142.11  2009-08-20    DELIVERED     Uttar Pradesh         3
142        143       628974          82  120.54  2023-05-05       PLACED           Haryana         2
143        144       735987          56  161.67  2000-10-15    DELIVERED            Kerala         3
144        145       529229          30  113.95  2015-11-01       PLACED         Karnataka         3
145        146       222491          38  119.78  2015-07-06    DELIVERED     Uttar Pradesh         1
146        147       494434           1  199.51  2022-05-08     RETURNED            Kerala         3
147        148        95240          45  180.79  2019-06-09       PLACED             Assam         3
148        149       377778          47  137.24  2012-02-28     RETURNED     Uttar Pradesh         1
149        150       514250          76  151.32  2021-02-07    CANCELLED  Himachal Pradesh         1
150        151       787512          88  160.39  2003-12-28       PLACED         Rajasthan         2
151        152       338503          78  158.73  2024-08-04       PLACED    Andhra Pradesh         2
152        153       905039          75  112.23  2016-06-15       PLACED         Karnataka         1
153        154       442922           6  198.01  2011-06-15      SHIPPED         Jharkhand         3
154        155       374480          61  137.00  2011-12-28    DELIVERED     Uttar Pradesh         2
155        156       992936           5  106.84  2009-09-23       PLACED               Goa         3
156        157        60603          81  184.39  2001-03-08    DELIVERED         Karnataka         2
157        158       742386          83  105.32  2019-11-25       PLACED        Tamil Nadu         3
158        159       261311          14  182.90  2005-02-23    CANCELLED             Bihar         3
159        160       486587          73  169.93  2005-08-13       PLACED      Chhattisgarh         1
160        161       217021          42  159.68  2022-07-05      SHIPPED               Goa         1
161        162        85399          88  168.16  2019-02-25    DELIVERED       West Bengal         2
162        163       832699          37  103.14  2017-05-23      SHIPPED    Andhra Pradesh         2
163        164       646863          48  185.81  2005-10-20     RETURNED            Punjab         2
164        165        30350          74  101.85  2009-06-11      SHIPPED        Tamil Nadu         1
165        166       623996          49  168.33  2009-01-28    DELIVERED         Telangana         3
166        167       893622           7  163.47  2015-04-10      SHIPPED        Tamil Nadu         3
167        168       337046          51  167.96  2021-04-09    DELIVERED      Chhattisgarh         1
168        169       152368          92  191.54  2002-06-17    CANCELLED       Maharashtra         3
169        170       558202          72  190.92  2008-09-19      SHIPPED         Rajasthan         2
170        171       966380          54  148.90  2019-08-31       PLACED         Rajasthan         2
171        172       166215          77  187.70  2004-10-07      SHIPPED            Kerala         2
172        173       540086          81  117.51  2010-01-06     RETURNED             Bihar         2
173        174       153562          24  153.48  2006-02-03    DELIVERED               Goa         1
174        175       297602          53  144.98  2000-02-05       PLACED         Rajasthan         1
175        176        31607          28  106.11  2001-02-16      SHIPPED       Maharashtra         1
176        177       485693          57  160.68  2018-07-16      SHIPPED    Madhya Pradesh         1
177        178       385486          23  114.72  2019-04-19    DELIVERED         Jharkhand         3
178        179       180568           4  176.97  2018-08-24       PLACED         Telangana         3
179        180       886074          62  182.84  2005-05-19    DELIVERED       West Bengal         2
180        181       768049          75  120.50  2023-08-18    DELIVERED         Jharkhand         1
181        182          715          61  129.21  2009-05-23       PLACED            Punjab         3
182        183       160863          43  124.76  2015-01-29       PLACED    Andhra Pradesh         1
183        184       962733          31  189.74  2005-08-10     RETURNED        Tamil Nadu         1
184        185       292065          85  162.34  2011-07-08       PLACED           Gujarat         2
185        186        58591          57  122.50  2023-11-05      SHIPPED             Delhi         1
186        187       216765          53  119.34  2015-06-02      SHIPPED             Delhi         2
187        188       317916          25  145.52  2016-02-29       PLACED       Maharashtra         1
188        189       396412           8  114.06  2010-07-20    DELIVERED       Maharashtra         3
189        190       279905          26  108.64  2017-11-23      SHIPPED         Telangana         3
190        191       352789          98  153.52  2012-05-10    DELIVERED             Delhi         3
191        192       682641          94  141.59  2010-11-15       PLACED            Kerala         3
192        193       813344          63  178.08  2013-06-15       PLACED             Bihar         2

### This is how you read a csv  this maitnian structured of the file

In [ ]:
import csv

with open("file.csv", "r") as f:
    reader = csv.reader(f)
    for row in reader:
        print(row)   # row is a list of columns